### ISSUE TITLE
Some appeals indeed included in the results

### ISSUE THREAD

**Issue by alokhmutov** [tochno-st/sudrfscraper#1]
Hi! It is so true that gathering court data is a pain. I am maintaining a database of prosecutions under art. 20.3.3 of the CAO (opposing the war), and have to use four distinct services such as this one to pull together the data. Will be happy to check this one out, too!

What I noticed right away is that sudrfscraper claims it found more cases than we currently have, and this is a bit suspicious. I will investigate further, but the first thing I see is that Readme states that sudrfscraper only collects first-instance decisions. 

However, I can see from the results that it also includes appeals from the Moscow City Court. Here is one example:

`[{"id"=>3398,                                                                                                                                    
  "region"=>77,                                                                                                                                  
  "name"=>"МОСГОРСУД",                                                                                                                           
  "caseNumber"=>"7-7703/2023 (1)",                                                                                                               
  "entryDate"=>nil,                                                                                                                              
  "names"=>"Привлекаемое лицо: Денисова Ж.Ф.&Ст. 20.3.3, Ч. 1&",                                                                                 
  "judge"=>"Лашков А.Н.",                                                                                                                        
  "resultDate"=>nil,                                                                                                                             
  "decision"=>"Завершено, 25.05.2023",                                                                                                           
  "endDate"=>nil,                                                                                                                                
  "text"=>                                                                                                                                       
   "Судья: Зиняков Д.Н.дело № 7-7703/2023\nРЕШЕНИЕ\n25 мая 2023 годаг. МоскваСудья Московского городского суда Лашков А.Н., рассмотрев в открытом судебном заседании дело по жалобе Денисовой Ж.Ф. на постановление судьи Хорошевского районного суда г.Москвы от 05 апреля 2022 года, которым Денисова Ж.Ф., *** года рождения, признана виновной в совершении правонарушения, предусмотренного ч. 1 ст. 20.3.3 КоАП РФ, ей назначено административное наказание в виде административного штрафа в размере 40000 рублей,УСТАНОВИЛ:\n04 апреля 2022 года должностным лицом ОУУП ОМВД России по району Строгино г.Москвы в отношении Денисовой Ж.Ф. был составлен протокол`

This is not the only one, there are quite a few appeals from MGS in administrative offence cases. (Identifiable by a number starting with "7-".) I think it would be helpful to indicate this in the Readme if this is something you intended to do, or maybe they were not supposed to get there. :) 

I suspect this happens because the service makes a request with an empty instance param:

https://www.mos-gorsud.ru/search?page=1&formType=fullForm&courtAlias=&uid=&instance=&processType=3&category=&letterNumber=&caseNumber=&participant=&codex=%D1%81%D1%82.+20.3.3&judge=&publishingState=&baseDecision=&documentType=&documentText=&year=&caseDateFrom=&caseDateTo=&caseFinalDateFrom=&caseFinalDateTo=&caseLegalForceDateFrom=&caseLegalForceDateTo=&docsDateFrom=&docsDateTo=&documentStatus=#

You can see if you follow the link that it includes a lot of appeals cases. 

But if you include the instance number, it is a different story:

`https://www.mos-gorsud.ru/search?formType=fullForm&courtAlias=&uid=&instance=1&processType=3&letterNumber=&caseNumber=&participant=&codex=ст.+20.3.3&judge=&publishingState=&baseDecision=&documentType=&documentText=&year=&caseDateFrom=&caseDateTo=&caseFinalDateFrom=&caseFinalDateTo=&caseLegalForceDateFrom=&caseLegalForceDateTo=&docsDateFrom=&docsDateTo=&documentStatus=#`

**Comment by courtandrey** [comment]
Hi! Thank you for this issue. When I was doing MGS, I thought that it would be a good idea to collect everything it provides (and completely forget to mention it, of course). Now I see that I should have made everything much more flexible. Now, with v0.2.5, instance is honestly configurable (for all courts, not only MGS), so I guess this issue is closed
