### ISSUE TITLE
Duplicate cases in MGS

### ISSUE THREAD

**Issue by alokhmutov** [tochno-st/sudrfscraper#2]
Hi, I believe there is another issue with MGS connected to #1. I can see that there are numerous duplicate cases:

```
[{"id"=>2990,
  "region"=>77,
  "name"=>"МОСГОРСУД",
  "caseNumber"=>"05-1545/2022 (1)",
  "entryDate"=>nil,
  "names"=>"Привлекаемое лицо: Фатфуллин Р.Р.&Ст. 20.3.3, Ч. 1&",
  "judge"=>"Семина О.Н.",
  "resultDate"=>nil,
  "decision"=>"Вступило в силу, 20.07.2022",
  "endDate"=>nil,
  "text"=>
   "судья фиодело № 7-11945/2022РЕШЕНИЕ20 июля 2022 годаадресСудья Московского городского суда...
```

```
{"id"=>3669,
  "region"=>77,
  "name"=>"МОСГОРСУД",
  "caseNumber"=>"05-1545/2022 (0)",
  "entryDate"=>nil,
  "names"=>"Привлекаемое лицо: Фатфуллин Р.Р.&Ст. 20.3.3, Ч. 1&",
  "judge"=>"Семина О.Н.",
  "resultDate"=>nil,
  "decision"=>"Вступило в силу, 20.07.2022",
  "endDate"=>nil,
  "text"=>
   "УИД 77RS0027-02-2022-012090-95\nДело №5-1545/2022\nПОСТАНОВЛЕНИЕ\nгород Москва,Каланчевская улица,...
```

The only difference is the decision text: one is by a first-instance court, another one by a judge deciding on the appeal. This may happen if each decision text on the case webpage is saved as a distinct case. But the first of the two cases above is not by judge Семина and not from case number 05-1545/2022.

**Comment by courtandrey** [comment]
Hi! As i mentioned in the previous issue: I've tried to collect everything MGS provided. Unfortunately, I misunderstood documents section in a case page. I thought it contains documents that are related to this specific proceeding, not all documents from previous or further proceedings, thus leading to duplicates. It is certainly an issue and I'll try to fix it in the following patch. Thank you for noticing!
